### ISSUE TITLE
Evaluate moving from docker-compose to k8s or mini-kube

### ISSUE THREAD

**Issue by junaruga** [FNNDSC/ChRIS_ultron_backEnd#228]
This is the ticket to manage the evaluation moving from docker-compose to k8s or mini-kube related to #227.

> RedHat endorses podman to replace docker. However podman does not support docker-compose. podman-compose does not work.

**Comment by mamurak** [comment]
Happy to help here, @bradscalio. Let me know if you need support.

I've had a quick look yesterday, and I was wondering whether we should set up a pair of deployment and service resources for each Cube component, so we can quickly start the whole system via kustomization. I'm not a k8s expert by any means, though. What would be your strategy?

**Comment by robpblake** [comment]
My experience here is that docker-compose is a far superior experience for local development. MiniKube/Minishift or CodeReady Containers are just too resource heavy and complicated. Is there a particular set of problems that are making docker-compose not suitable for local development?

**Comment by jennydaman** [comment]
The primary motivation here seems to be better support on Fedora 32 "out-of-the-box," though looking into other container orchestration solutions would also help make deployment more seamless.

**Comment by rudolphpienaar** [comment]
@robpblake -- as I understood this particular "issue", it relates to the difficulty in getting the current ChRIS ecosystem working on Fedora (and related) systems. At BCH our dev env is all Ubuntu and we've had no difficulty with docker/docker-compose etc (even on MacOS!) but folks wanting to get up and coming on Fedora have more difficulties de novo.

So, for us on Ubuntu no, there are no problems or issues :-)

**Comment by mamurak** [comment]
I've translated the CUBE services into k8s deployments and services ([link](https://github.com/mamurak/ChRIS_ultron_backEnd/tree/master/k8s_resources)). My attempt is still lacking volumes and networking, but I managed to deploy the services locally (except for the worker, which crashes randomly).

**Comment by junaruga** [comment]
@mamurak Thanks for the work! Can we add you as Assignees for this ticket with Brad?

**Comment by mamurak** [comment]
@junaruga Yes, you're welcome to add me.

**Comment by mamurak** [comment]
Adapted the k8s resources to establish connectivity between the services.

The worker had been crashing as it couldn't establish connectivity with third party services, but it is stable now. That was a tricky bit as it's reading its endpoint settings from config files that are built into the container. Simple volume mounting doesn't work on my system (kvm on minikube doesn't support that yet, apparently), so I'm currently using my own registry as a workaround.

Even though the services can communicate with each other, pfcon's `hello` command is failing (connection abort).

[Current state](https://github.com/mamurak/ChRIS_ultron_backEnd/tree/master/k8s_resources).

TODOs:
* Verify integration by enabling pfcon's `hello` command.
* Find a more sustainable solution for configuring the worker's service settings.

**Comment by mairin** [comment]
This was discussed in this morning's status meeting. @rpienaar suggested updating pfcon - it won't address the `hello` command issue, but the way it communicates to swift has changed in the past 3 days.

Suggestion for the `hello` command issue... try testing the system by setting up the components via the make script and see if `hello` is working in that environment too, so we can see if `hello` is the issue or if its something to do with the environment.

@mamurak asked if there was a simpler debugging mechanism than trying to run `hello` - @rudolphpienaar suggested looking at the wiki page that talks about debugging pfcon pman pfioh, it is a little bit old but it might have a suggestion. We mostly use `post`, but `get` should work. Not a real proper REST service - essentially everything is a `post` and it interprets the JSON payload to determine what to do, so it doesn't actually use the verbs... eg GET PUSH etc., uses the JSON instead:

- make sure pfcon running in an interactive terminal
- put in some breakpoints
- see if it's actually getting to the `hello`

Each JSON sent has:
- an action
- a meta
The action gets evaluated. An action like `hello` - the actual piece of code that services that is a piece of code called hello_process. The main entry point in any POST request is the do_post method... put a breakpoint there, and could see if it's getting there. 

@mamurak 2 questions:
- a large dict called internal variables, and the option to insert options through it... sometimes i get mixed up which is being read. Can I disregard that part? @rudolphpienaar says you can disregard the huge dictionary... is legacy, was based on how a python base class was limited in how it could get data, was a hack for how things used to work. Safe to ignore it.
- line 1590-1600 - main method is `do_post` - if you send it a well-formed JSON payload, it should hit that method. there's a commented out breakpoint near there in the code... uncomment that breakpoint and hit it with requests. Suggest using `pdb` as a debugger.
- log verbosity is set to 1, is that sufficient or could it be changed? @rudolphpienaar says it's chatty so that should be sufficient. Make sure you're running pfcon interactively. @mamurak is using the kubernetes webui built in interactive terminal and has it hooked up to STOUT for the container. you should be seeing a lot more activity in this log. 
- if at some point we want to do centralized logging, may need to format in a different way. right now logging is handled by a diff module called pfmisc. One of the summer interns was working to use the python logging mechanism to do all logging instead of what we currently have, so there's some progress towards that. 

Next Steps:
- Make sure you are running the latest version of the components
- Try running pfcon using the interactive shell
- @rudolphpienaar will give it a try as well locally, give it a `hello`, and check in with @mamurak and they can compare results

**Comment by mamurak** [comment]
The `hello` command is working. It was working all along. It turns out my test requests triggered a nasty bug in the _cgi_ module, one that's known for several years ([link](https://bugs.python.org/issue27777))...
In essence, the content type of the hello request must be `application/x-www-form-urlencoded`, otherwise a type error is encountered due to inconsistent file handling during payload registration. Despite the fact that `hello` expects a JSON request body, neither the `application/json` nor the `application/vnd.collection+json` content type can be handled by `pfcon`.

Next steps:
* Prepare pull requests.
* Adapt [documentation](https://github.com/FNNDSC/pfcon/wiki/pfcon-command:-hello).

**Comment by mamurak** [comment]
`pfcon` needs to be adapted as it currently contains hard coded host names of third party services that are incompatible with Kubernetes. Created required issue https://github.com/FNNDSC/pfcon/issues/74.

**Comment by jbernal0019** [comment]
I totally agree with @robpblake. `docker-compose` has proven to be the simplest and fastest tool for local development.  

Nevertheless we have a mix between `docker-compose` and swarm/kubernetes deployments for local development of CUBE because the satellite services `pman` and `pfcon`  require to be deployed within a compute cluster (swarm/kubernetes). This also allows us to more accurately simulate the fact that `pman` and `pfcon` could be independently deployed in a "far away" swarm/kubernetes cluster. 

But keeping CUBE development within `docker-compose` still makes things much easier.
